name: Run Tests for Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout page source
      uses: actions/checkout@v3

    - name: Build the Docker image and run tests
      run: docker compose -f "compose.test.yaml" up -d

    - name: Print Logs for Container
      run: |
        export CONTAINER_ID=$(docker ps -aqf "name=ci")
        docker logs -f $CONTAINER_ID | while read line ; do
          echo $line
          if echo $line | grep -qi 'assertion'; then
            exit 1
          fi
        done || true
